### ISSUE TITLE
Confusion between `npl_publn_id` and `when` fields

### ISSUE THREAD

**Issue by gderasse** [cverluise/SciCit#1] opened 2019-10-14 15:00 UTC
Sometimes, the field "when" takes the value in field "npl_publn_id" (see, e.g., npl_publn_id 1003)

**Comment by cverluise** [comment] 2019-11-18 20:13
We proceed as follows:

1. we detect the issue
2. we report the issue (#1) in `Issues`

Nevertheless, we do not change the `when` for 2 reasons:

- if the  value in `when` is not a date compatible format (e.g. 123456), it won't be used in the `year` field. In this case, the issue is harmless.  This is likely to be the majority of the cases. 
- the value in `when` might well both contain the `npl_publn_id` and  be a valid date (e.g 1890). 

I close the issue. Feel free to re-open it if needed. 

Cheers

**Closed by cverluise** 2019-11-18 20:13 UTC
Labels: beta, parsing
